<a href="https://colab.research.google.com/github/lrtipple/Credit_Risk_Analysis/blob/main/credit_risk_ensemble.colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [4]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [5]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [6]:
# Load the data
file_path = Path('/content/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [7]:
# Create our features
X = pd.get_dummies(df, columns=['initial_list_status',
    "home_ownership",
    'verification_status',
    'issue_d',
    'pymnt_plan',
    'next_pymnt_d',
    'application_type',
    'hardship_flag',
    "debt_settlement_flag"]).drop('loan_status', axis=1)

# Create our target
y = df['loan_status']

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Feb-2019,issue_d_Jan-2019,issue_d_Mar-2019,pymnt_plan_n,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.371696,0.451066,0.177238,1.0,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.483261,0.497603,0.381873,0.0,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,1.000000,0.000000,1.0,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [9]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

X_train.shape

(51612, 95)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier


# Instantiate
brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fit
brfc.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [12]:
# Calculated the balanced accuracy score
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.8025897479832174

In [13]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual high_risk", "Actual low_risk"], columns=["Predicted high_risk", "Predicted low_risk"])
cm_df

                  Predicted high_risk  Predicted low_risk
Actual high_risk                   75                  26
Actual low_risk                  2350               14754

In [14]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.74      0.86      0.06      0.80      0.63       101
   low_risk       1.00      0.86      0.74      0.93      0.80      0.65     17104

avg / total       0.99      0.86      0.74      0.92      0.80      0.65     17205

In [15]:
# List the features sorted in descending order by feature importance
features_rank = sorted(zip(brfc.feature_importances_, X.columns), reverse=True)
for feature in features_rank:
    print(f"{feature[1]}: ({feature[0]})")

total_rec_prncp: (0.07685363116921974)
total_pymnt_inv: (0.06048806484293307)
total_rec_int: (0.059887592569235176)
total_pymnt: (0.05244156205506048)
last_pymnt_amnt: (0.04753892371077525)
int_rate: (0.027796059781553945)
issue_d_Jan-2019: (0.02294317077696126)
mths_since_recent_inq: (0.01998346590422108)
installment: (0.017549216204620795)
out_prncp: (0.017010659401497305)
loan_amnt: (0.016874891375863635)
max_bal_bc: (0.01676154381445895)
dti: (0.016408343298626168)
out_prncp_inv: (0.01632065128135565)
mths_since_rcnt_il: (0.015680086503620135)
mo_sin_old_il_acct: (0.01517402648651458)
il_util: (0.014828996160654213)
avg_cur_bal: (0.01473084020732434)
total_bal_ex_mort: (0.014520684981874945)
tot_hi_cred_lim: (0.014473378484395517)
total_rev_hi_lim: (0.014244702113285912)
annual_inc: (0.014170962091621237)
bc_open_to_buy: (0.013830768751886775)
revol_bal: (0.013682560546235756)
bc_util: (0.013531203414924729)
issue_d_Mar-2019: (0.01324470686455325)
tot_cur_bal: (0.012943122299459943)
total_il_high_credit_limit: (0.012805981391123388)
total_bal_il: (0.012357271682482981)
mo_sin_old_rev_tl_op: (0.012122596431718773)
total_acc: (0.011678031329773799)
num_il_tl: (0.011251098468380382)
num_rev_accts: (0.011153214638845015)
total_bc_limit: (0.010978393550914702)
mths_since_recent_bc: (0.010926263102493314)
inq_last_12m: (0.010594921338898108)
open_acc_6m: (0.010556291820083283)
all_util: (0.010335521196214068)
num_bc_sats: (0.009050952657621132)
mo_sin_rcnt_rev_tl_op: (0.008895623934882703)
num_bc_tl: (0.00885499945947619)
acc_open_past_24mths: (0.008457058696492032)
num_actv_rev_tl: (0.008419291817110713)
num_op_rev_tl: (0.008315874189892523)
inq_fi: (0.008254684647658208)
open_acc: (0.008136577895853307)
pct_tl_nvr_dlq: (0.008102961365237117)
num_sats: (0.007894357531403972)
mo_sin_rcnt_tl: (0.007845885707749599)
num_rev_tl_bal_gt_0: (0.007556578508812849)
num_tl_op_past_12m: (0.006961757895958144)
open_rv_24m: (0.006807475270360265)
open_act_il: (0.006630186404583741)
num_actv_bc_tl: (0.006412823269256503)
total_cu_tl: (0.006197777988769285)
open_il_24m: (0.006182344321469785)
mort_acc: (0.0061510060339371566)
percent_bc_gt_75: (0.006134267396347057)
total_rec_late_fee: (0.005931054050256411)
inq_last_6mths: (0.005792076129198295)
open_il_12m: (0.005551355446940886)
open_rv_12m: (0.005131807434291977)
next_pymnt_d_May-2019: (0.004984660564444257)
issue_d_Feb-2019: (0.004929853554780033)
next_pymnt_d_Apr-2019: (0.004511557244988563)
delinq_2yrs: (0.0040325448623642485)
tot_coll_amt: (0.003993771683479881)
home_ownership_MORTGAGE: (0.003660962720350823)
pub_rec_bankruptcies: (0.002433685527229652)
verification_status_Not Verified: (0.0023864293136772433)
num_accts_ever_120_pd: (0.0020011643703071414)
pub_rec: (0.0019659969872225236)
home_ownership_RENT: (0.0018400158383343513)
application_type_Joint App: (0.001570370988062648)
application_type_Individual: (0.0015559823172233624)
num_tl_90g_dpd_24m: (0.0014294618422762287)
verification_status_Verified: (0.0013971439131693119)
verification_status_Source Verified: (0.001267346146859799)
home_ownership_OWN: (0.0011275556214494222)
initial_list_status_f: (0.0010536972303488385)
initial_list_status_w: (0.0008261395446540065)
collections_12_mths_ex_med: (0.0004266717733280721)
home_ownership_ANY: (0.00019849436825273282)
chargeoff_within_12_mths: (6.431548997551773e-05)
tax_liens: (0.0)
recoveries: (0.0)
pymnt_plan_n: (0.0)
policy_code: (0.0)
num_tl_30dpd: (0.0)
num_tl_120dpd_2m: (0.0)
hardship_flag_N: (0.0)
delinq_amnt: (0.0)
debt_settlement_flag_N: (0.0)
collection_recovery_fee: (0.0)
acc_now_delinq: (0.0)

### Easy Ensemble AdaBoost Classifier

In [17]:
!pip install scikit-learn==1.0 -U

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting scikit-learn==1.0
  Downloading scikit_learn-1.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (23.1 MB)
     |████████████████████████████████| 23.1 MB 2.0 MB/s
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (3.1.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==1.0) (1.21.6)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
Successfully installed scikit-learn-1.0

In [16]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
# Instantiate
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)

# Fit
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [17]:
# Calculated the balanced accuracy score
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9323031958247274

In [18]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual high_risk", "Actual low_risk"], columns=["Predicted high_risk", "Predicted low_risk"])
cm_df

                  Predicted high_risk  Predicted low_risk
Actual high_risk                   93                   8
Actual low_risk                   961               16143

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205